import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Login from "../components/Login";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" ">
        <Header />
        <Login />
      </main>
    </div>
  );
}
